### ISSUE TITLE
Wallet is unusable as private key is blurred on printout

### ISSUE THREAD

**Issue by hrishikeshio** [ryepdx/ethaddress.org#18]
Ubuntu 15.10 x64 on latest chrome. Printout have blurred private key qr code.

**Comment by hrishikeshio** [comment]
![image](https://cloud.githubusercontent.com/assets/1659870/12374073/c3bc3824-bcb6-11e5-97b6-b0e5d09cb9f5.png)

**Comment by ryepdx** [comment]
Thanks for opening this issue and providing a screenshot. I'll get on this tomorrow.

**Comment by ryepdx** [comment]
Should be fixed now. Please clear your cache, reload, and let me know if it's working for you now.

**Comment by hrishikeshio** [comment]
Works on firefox. on chrome, however, when I click print, the print dialog never loads. Its stuck on Loading preview.. screen.

**Comment by hrishikeshio** [comment]
Never mind. It works now. Thanks.
