### ISSUE TITLE
Invalid public key / private key generated

### ISSUE THREAD

**Issue by bokkypoobah** [ryepdx/ethaddress.org#19]
Thanks for your software.

I used the bulk create function to create 80+ address pairs so I could choose a few nicer ones out of them. For the ones I chose, I entered the unencrypted private keys into MyEtherWallet and later Geth to check that the same public key is created. 

One of the pairs I tested came up with a different public key in both MyEtherWallet and Geth. 

Here is the pair generated by ethaddress.org downloaded onto my computer:
46,"0x888358a26844bc873ebcec943ce4e04ed3cfd79a","fc8958b6388c35821999ffdec3fc06acf481373b4f788cf27571b26ead66e885"

When I entered the generated private key into MyEtherWallet, the public key generated was "0x40dd9e757faf28fe20e5961ba968a824898234c4"

When I imported the generated private key into Geth, Geth generated the following public key: {40dd9e757faf28fe20e5961ba968a824898234c4}.

The other 8 pairs generated by your ethaddress.org software were consistent when checked against MyEtherWallet and Geth.

I can reproduce this issue by entering the generated private key back into the ethaddress.org page. The generated public key is 0x888358a26844bc873ebcec943ce4e04ed3cfd79a .

**Comment by bokkypoobah** [comment]
Here is a screenshot with the generated private key imported into the ethaddress.org page.

Sorry, but I can't seem to upload the screen print into this github comment.

**Comment by ryepdx** [comment]
Thanks for the heads up.

**Comment by Ethmann** [comment]
Did you solve the problem in the last days? I created 85 wallets with the bulk wallet generator to CSV and I tested each Private Key on MyEtherwallet.com ! Couldn't find any Invalid Key Pairs!

**Comment by ryepdx** [comment]
It looks like you've found a really interesting edge case, to be honest. No, I haven't solved the issue yet. I'll see what I can figure out, though.

**Comment by ryepdx** [comment]
Okay, I finally managed to un-break my EthAddress.org environment. Basically it looks like the problem was being caused by an outdated dependency. Pushing a fix now.

**Comment by bokkypoobah** [comment]
Great work. Thanks.
