### ISSUE TITLE
Add support for vanity address generation?

### ISSUE THREAD

**Issue by whitj00** [ryepdx/ethaddress.org#7]
See https://github.com/whitj00/ethereum-vanity

**Comment by ryepdx** [comment]
Thanks for the feedback and the code! Going to have to refocus on paid work for the next couple days, but I'll get this implemented as soon as I get a chance.

**Comment by whitj00** [comment]
Maybe I'll make a PR :)

**Comment by ryepdx** [comment]
PRs are always welcome! Let me know if you have any questions or need help with anything. :-)

**Comment by ryepdx** [comment]
And done! Thanks for the code example and the request.
